### ISSUE TITLE
Grashopper: Publish View lense length vs field of view

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#106]
The Field of view input is behaving very different from the Rhino Lense length. It would be great if this would also be the lense length, otherwise it is very difficult to get consistency between the rhino views and the ones from GH.

**Comment by Archtica** [comment]
Yes, the Rhino side should use only lense length and then do the conversion later. I just got lazy when making it. (Unity is field of view based) Good point!

**Comment by Archtica** [comment]
Featured in next beta
