### ISSUE TITLE
C Plane used confused

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#109]
When using a custom c-plane in Rhino. This is ignored but not communicated, a circumstance that is confusing. It would be great if one would be told that the c-plane used by Radii is the standard and deviates from the one currently in use in Rhino.

**Comment by Archtica** [comment]
Hi G, I'm not exactly sure I know what you mean here? If I use a custom c-plane to draw the geometry it is corretly aligned with the world in the viewers.

**Comment by gesievi** [comment]
Hey Thomas, so this means that the custom c plane from the rhino session becomes the de facto default reference grid ? 
Because when i worked with one the other day the geometry seemed to appear further away from the 0,0,0 than anticipated until i changed back into the top Cplane in rhino that seemed to correspond more precisely with the one in the viewer.

**Comment by Archtica** [comment]
I've set my cplane byt object for example, but it puts the geometry in the right place. Is it somewhere else that you set the custom c-plane?

**Comment by gesievi** [comment]
![image](https://github.com/Archtica/RADii/assets/45074510/b48d0749-ebcc-4de8-b74f-826e639fefd8)

It is possible to define new global c planes. This can be helpful for geolocated models. When using the non standard World Top C-plane (that is not the object relative one) The World is used. This has lead to confusion recently in a file. I dont think that this needs urgent action, it more of a point i wanted to bring to your attention. 

Greetings

**Comment by Archtica** [comment]
Hi G I know about named c-planes, but I didn't know you could set a new global. I've never used anything else but the default and then the regular custom once set by object.

**Comment by Archtica** [comment]
Hi G, I was just looking at it and it is behaving like it should in my opinion. The construction plane is just that. A plane where  elements are constructed relative to. The geometry is still in the absolute world 0,0,0. The construction plane is just a "helper" for constructing elements. If you move something by entering a coordinate you can put "w" in front and it will move relative to the world coordinate system if not it is relative to the construction plane.
How should the viewers react to changing the construction plane?

**Comment by gesievi** [comment]
I think you have a good point here i would close the issue.
