### ISSUE TITLE
v. 3.38.3 Viewer pc sound sounds like a vinyl sped up/ down

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#110]
When running to or away from a soundsource it sounds like a vinyl beeing speed up and down. The pitch goes up and down.
This is less of a problem for noise, but for music or tonal sounds, it is very obvious.

Link for the music.: https://ia801701.us.archive.org/2/items/17-futura-free/01%20Nikes.mp3

Note: Spaces seem to be substituted as % by grasshopper.

**Comment by Archtica** [comment]
This is the sound of the dopler effect. I will reduce it.
