### ISSUE TITLE
v. 3.38.3 GH Publishsound Link issues

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#111]
When using the following link: https://archive.org/details/17-futura-free/01+Nikes.mp3 
the publish sound component does not work.
When using the dedicated mp3 link from the same website it does work however. If the above link is one to an mp3 maybe it does not work because of the + ? i thought this was a curious bug. Hopefully we do not have any bigger syntax issues here.
https://ia801701.us.archive.org/2/items/17-futura-free/01%20Nikes.mp3
(this one works)

**Comment by Archtica** [comment]
If you right click the first link and try and save it, it tries to save a html page, so it is not an mp3 it just looks like it. The last one is a real mp3.
