### ISSUE TITLE
v. 3.38.3 Viewer Stop on exit does not work

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#112]
Stop on exit does not work for me. 
![image](https://github.com/Archtica/RADii/assets/45074510/f5914ec5-8fa1-4e65-a9c8-3b31069ba003)
![image](https://github.com/Archtica/RADii/assets/45074510/f6c2561f-e80d-42a2-8afa-b3509f43b172)

**Comment by gesievi** [comment]
Correction: it does work but only when play on enter is on and play off.
I think it would be good if the combinations would work as well that the sound is playing from the beginning, but upon leaving the area it stops.

**Comment by Archtica** [comment]
I will make that an option too. Rigth now on exit is conditioned by on enter, but I will disconnect them.
