### ISSUE TITLE
v 3.38.4.0 Beta Reference manager invisible 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#115]
When loading a reference with active on and visible off and then turning visible on, it does not become visible. Instead it is necessary to flip visibility on and off again to turn it on.

**Comment by Archtica** [comment]
Is this when loading directly in the reference manager og loading via a scenario?

**Comment by Archtica** [comment]
I see the error and why. I'll fix it tonight.

**Comment by Archtica** [comment]
Fixed
