### ISSUE TITLE
v0.38-beta.4 publish reference publish controll bug

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#117]
1. _A batch of references_ is loaded invisible into the scene
2. _First half_ of the references are quickly Toggled visible - NO EFFECT STILL INVISIBLE
3. _All references_ are quickly toggled visible - ONE SMAL REFERENCE VISIBLE FROM STEP 2 is visible
4. going back between 2. and 3. yields no results
5.  CLEAR 
6. A _batch of references is loaded_ invisible into the scene
7. WAIT 2-3 seconds
8. _First half_ of the references are Toggled visible- NO EFFECT STILL INVISIBLE
9. _All references_ are quickly toggled visible - SECOND HALF IS VISIBLE
10. _First half_ of the references are Toggled visible- HIDES SECOND HALF BUT DOES NOT SHOW THE FIRST
11. _LOAD_ AGAIN
12.  _First half_ of the references are Toggled visible- **SHOWS REFERENCES SUCCESSFULLY** 
13.  _All references_ are quickly toggled visible - **SHOWS ALL REFERENCES SUCCESSFULLY**

This could be a reminand of the already closed #115 

https://github.com/Archtica/RADii/assets/45074510/289c4be0-86d9-4a21-b590-af8b8e912f46

**Comment by Archtica** [comment]
Thanks G!
The fix that I just did definitely solves the initial not coming on. Keep the scenario test that you just showed around and then I will upload a new beta tonight. Then run the test again. I will also try again.

- Are you by any chance also changing the active status of the reference or is it on in both scenarios only changing visibility?

- Maybe the large references haven't finished downloading before you trigger the next scenario (see the download progress in the top menu). They are stacked in a download queue. That has also been taken care of in the latest beta. Should you change the visibility of a reference already in the download queue  will actively change the visibility status in the download queue. I think this is what we are seeing.

**Comment by Archtica** [comment]
Fixed in new beta
