### ISSUE TITLE
Radii_v0.38.b5 Reference manager menu issue

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#119]
Reproducable only one windows device.

When opening the reference manager it first works. 
After clicking into the Rhino window the menu gets stuck and prevents a new reference window to open. 
Pulling new publish reference components into the file somewhat works as a workaround. Each new publish reference component can however only be opened once and then gets stuck in the above described mode.

**Comment by Archtica** [comment]
I will look into the menu focus code.

**Comment by Archtica** [comment]
Let me know if it happens consistently

**Comment by gesievi** [comment]
it happens consistently. On my device to. I am up to date. Opening the ref. manager works fine, after going into the rhino window and coming back opening the ref. manager ist not possible anymore. The button does not seem to react anymore.
![grafik](https://github.com/Archtica/RADii/assets/45074510/9a8ab9e9-d94a-49bf-837f-4f3e220b3527)

**Comment by gesievi** [comment]
using a new component works but only until the bug re appears.
seems like this is not a bug that happens to everyone, since i have not gotten any reports beside one group.

**Comment by Archtica** [comment]
Thanks I will fix it. I'm testing a new menu approach in the reference menu, that apparently has issues. I will fix it asap.

**Comment by Archtica** [comment]
I see the issue, it is when using the X in the top right corner when closing the menu. If you use the close button in the menu it does not happen. X forces a "hard close" apparently. I will fix it.

**Comment by Archtica** [comment]
Fixed in latest release
