### ISSUE TITLE
Radii_v0.38.b5 Publish animation path

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#120]
The curve between animation planes is always interpolated, in cases of machine movements this seems a bit strange, we could use an option for polilines. for example a storage elevator first goes sideways and then moves vertically up. Instead of having to do two animation, this could be done in one with a polyline pathway.

**Comment by Archtica** [comment]
Good idea! It will be a matter of chaging the degree on the interpolation. I will look into that!

**Comment by gesievi** [comment]
great to hear would be very helpfull. we have to work with a workaround right now that is quiet a bit of work.
