### ISSUE TITLE
Radii_v0.38.b5 Publish curve

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#121]
Observed on one mac system.

A file that was written in v0.38.b4, but the update to b5 was done.
Upon trying to delete publish curve, the file and rhino, instantly crash. After doing so twice, the file is so curruped that it shows up empty.

Solution was to evacuate all other components to another file.

**Comment by Archtica** [comment]
The curve component does not write anything to the gh file, so it must have been something else. What other components were in the file? Often Rhino dumps a crash file on the desktop. Do you have that?
