### ISSUE TITLE
subsrice user plane hight

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#125]
When subsribing to a user, the head plane is not correctly aligned with the view but slightly above. When using these planes with publish views this leads to slight hovering above the ground plane.

**Comment by Archtica** [comment]
thanks, I can reproduce. When using surfaces it is centered, but when using planes the center is at 1,1 on the plane and not 0,0. I've had this before and thought that I fixed it.

**Comment by Archtica** [comment]
Fixed 0.38.7
