### ISSUE TITLE
GH version display

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#131]
there is no display of the version of gh you are running, i think it would be good to have it in the connect menue displayed among the channel etc. 
![grafik](https://github.com/Archtica/RADii/assets/45074510/70659103-f3f8-44b9-afe0-58c199feb17b)

**Comment by Archtica** [comment]
When connected you can see the plugin version here:
![image](https://github.com/Archtica/RADii/assets/33350816/450b81fe-fef7-463e-9a71-907c51648f83)
