### ISSUE TITLE
Inverse by default of 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#134]
In our use cases we have so far not found a use for inverse on and are always turning it of first. We think it could be of by default when starting the viewer or, remember the setting when opening a new viewer.

**Comment by Archtica** [comment]
I will make it so that it remembers it. For usability I would like to keep it initially on for new users as it is easier to understand. Good comment, it is on the list.

**Comment by gesievi** [comment]
this issue persists, is it still on the list ?

**Comment by Archtica** [comment]
The setting for inverse section is on by default, but the setting will be remembered between sessions

**Comment by gesievi** [comment]
The remembering part does not work for my version.

**Comment by Archtica** [comment]
Hi G, I just added it last night so it will be in the next release. I just uploaded to Apple so hopefully very soon.
