### ISSUE TITLE
c38.6 Field ov view issues

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#136]
1. In Publish view the Field of view input does not influence the field of view in radii 
![image](https://github.com/Archtica/RADii/assets/45074510/441a22fa-fea2-4d49-bc2a-1e05fff4b1a1)
![image](https://github.com/Archtica/RADii/assets/45074510/c48a5cd0-f106-4d33-ae1e-da65928a52e8)

2. Publish Animation seems to take the last or different field of view this means that when playing an animation (lense ca. 50) then a view (lense different) and then a second animation, that it is having a different lense all of a sudden since it seems to take the one from the view.

**Comment by Archtica** [comment]
I'll look into it. A fix for now is to use named views and not view planes.
I think animations are locked to 60 degrees field of view. I never implemented custom FOV I can see.

**Comment by Archtica** [comment]
Fixed in next beta
