### ISSUE TITLE
v38.8 Curve publish CRASH

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#137]
![image](https://github.com/Archtica/RADii/assets/45074510/6f60eb83-658b-4058-89eb-38dbb0d704d3)

reported by a student:
grasshopper crashes with this message when disconnecting the publishCurve component.

This is only since the new update they report.

**Comment by Archtica** [comment]
Thanks I discovered this the other day too and fixed it. I will upload a new plugin tomorrow.

**Comment by Archtica** [comment]
Fixed
