### ISSUE TITLE
Publish view - change of views stuttering

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#139]
When changing from one view to another the field of view changes for one or two frames which leads to the impression of stuttering. this is especially visible when doing recordings of presentations but also during.

**Comment by Archtica** [comment]
I've never made them gradual because I don't know what the duration should be. Maybe a fraction off the entire duration is a good idea without adding a new duration option

**Comment by Archtica** [comment]
Add smooth animation for field of view change in next beta
