### ISSUE TITLE
v 29.b2 Publish curve - curve input error

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#142]
When giving a list of curves and line like curves the component is not taking the curves no more. It works with a list of referenced ones but it did run without a problem before the last update.
Tested with local and global connect - no difference.

![image](https://github.com/user-attachments/assets/c7ff3ae8-971a-4bd1-b433-4111156e8cb8)

**Comment by gesievi** [comment]
when backing and referencing curves all goes well, but the moment i internalize them the error message is there again and the component seems to be ignore the input.

**Comment by gesievi** [comment]
Error message
1. Solution exception:Object reference not set to an instance of an object.

**Comment by Archtica** [comment]
Thanks G, fixed in next update. It was related to the transformation.

**Comment by gesievi** [comment]
Always a pleasure.
Thank you for the quick fix.

🥇
