### ISSUE TITLE
v 39b2 Grashopper slow

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#143]
Since the update 39b2 my grasshopper has been very slow to start and when deleting a referenced geometry in Rhino on a local connection RADii settup my Rhino session froze for 2 minutes

Does this appear for you as well ?

**Comment by Archtica** [comment]
Hi G, No I have not had the same issue and it starts just as fast as ever, but I have not tested it as much as you. It sounds like a network thing.

- Are you running the viewer on the same computer ip 127.0.0.1 or on the LAN?
- Is it a heavy model you are working with?
- Is it consistent or only sometimes depending on network setup home/work?
- Are you running on Rhino 7?

**Comment by Archtica** [comment]
When I get to my stationary computer tomorrow I will send you the latest plugin. I did some changes that may resolve some of your issues.

**Comment by Archtica** [comment]
I discovered some other issues with the local connection on macos, so I'm redoing the entire thing.

**Comment by Archtica** [comment]
This should be fixed in the latest beta
