### ISSUE TITLE
Pepperghost viwer not centralized

### ISSUE THREAD

**Issue by Archtica** [Archtica/Radii#144]

**Comment by Archtica** [comment]
What do you mean with this? Is it the 0,0,0 that is not in the center of the box? I discovered that too and it has been fixed in the next release, if it is that?

**Comment by gesievi** [comment]
to be honnest i was wondering what you meant with this ever since you opened the issue :)

**Comment by Archtica** [comment]
Haha, I forgot that I put it in! I thought it was you. I'm starting to have conversations with myself... how nice.
The other night I was searching for a solution to an issue and I found a forum where a guy had the same issue and a good solution. So I wrote the guy to say  thank you until realized it was myself two years ago...

**Comment by gesievi** [comment]
This just became my favorite bug of all time thomas you made my day ahahahhah

**Comment by Archtica** [comment]
I agree with myself and I, that this issue is now successfully resolved! 🥇
