### ISSUE TITLE
v 39.3b Publish Pointcloud solution exception: source array not long enough 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#147]
![image](https://github.com/user-attachments/assets/4b66f5c6-e360-43e7-a3ac-e52dbd7f09eb)
When using a pointcloud (grid of 1000000 p) it throws the following error, with both connect components.

**Comment by Archtica** [comment]
How many points in total? You can only have (2^32)-1 points as of now.

**Comment by gesievi** [comment]
1000000 p
 But i tried multiple upward of 1000

**Comment by Archtica** [comment]
Ah ok, I thought there were more. It something about how the component deals with points. I'm running it across threads and it doesn't like that with that many it seems. I will investigate what can be done.

**Comment by Archtica** [comment]
It's strange because I've easily worked with 30mil. points before. https://www.instagram.com/p/CWoB6N6l8S-/?hl=da
Are you selecting a true point cloud in Rhino or a series of point. If not the try converting the points to a point cloud in Rhino before selecting it.

**Comment by Archtica** [comment]
Here I'm selecting 32mil points with no issue. What does the point cloud look like in Rhino (see above):
![image](https://github.com/user-attachments/assets/34dab4f5-b2e3-415b-9d22-51279ed83e64)

**Comment by gesievi** [comment]
mine is significantly smaller at 992 337 points. I generated them from a 3d point grid that i then converted into a pointcloud, thinking it would be an easy test case for pointcloud and then ran into the mentioned error message.
![image](https://github.com/user-attachments/assets/6c22c256-a769-4190-a5a4-1430c3059769)

**Comment by Archtica** [comment]
Can you send me the rhino file that has the point cloud you are selecting? I really want to know what is going on with that particular one. As long as it is a point cloud from rhino it should not complain like it is doing. It can also take a raw point of list, but it's much heavier.

**Comment by gesievi** [comment]
[Test Setup.zip](https://github.com/user-attachments/files/16614801/Test.Setup.zip)

**Comment by Archtica** [comment]
Fixed in coming v0.40 . It is because the point cloud has no color and I need to check for that.
