### ISSUE TITLE
Views in scenarios dont change when parent changed

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#15]
Views saved in Scenarios don’t change anymore since the BETA Version if their “original” in Rhino is changed. That was very helpful to adjust Views in a Presentation afterwards.

**Comment by Archtica** [comment]
This works on my end when saving over an existing named view with same name. There will be a prompt about replacing the existing and you hit OK. The change is reflected in the viewer.

**Comment by gesievi** [comment]
I think you can mark this as solved. This is an old bug.

**Comment by gesievi** [comment]
I think we can close this issue at this point
