### ISSUE TITLE
v40.3 Publish controll dissapearing

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#155]
When ever  i open a new file the publish control component is gone. I then have to drag in a new component and it works.

**Comment by Archtica** [comment]
Hmm, that is strange. Do you get any error and is it the same for students too? Sometimes Rhino puts a small error file on the dekstop. I will also investigate.

**Comment by gesievi** [comment]
ill check in with the students, they are not at that point yet. not error file for me.

**Comment by Archtica** [comment]
Thanks, I'll also check.

**Comment by Archtica** [comment]
Hi again G, are you mayby trying to open an old control component that has scenario content from when the scenario was part of the control component?

**Comment by gesievi** [comment]
hey, thanks for checking in, ill try replacing all components of the file with new ones. There might be an old component flying around :)

**Comment by Archtica** [comment]
That, or you are opening an old GH file from a previous control component into the new one. Back then they had all information about scenario inside them and that might conflict with the current component.

**Comment by gesievi** [comment]
so jonas has the same issue. he just came to me as well. have you been able to reproduce this issue ?

**Comment by Archtica** [comment]
Thanks G, not yet, but I'll check it out tomorrow!

**Comment by Archtica** [comment]
Fixed in next beta

**Comment by gesievi** [comment]
Legend.


Am 24.10.2024 um 21:02 schrieb Thomas Lee ***@***.***>:

﻿

Fixed in next beta
