### ISSUE TITLE
v 40.3 Publish view

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#156]
The timer of publish view resets after each opening. meaning that it has to be timed anew at each opening of the file. Say for example while working on multiple views and taking a break or setting them up for a presentation is very inconvenient.

**Comment by Archtica** [comment]
Thanks G, I will make the changes persitent. I'm trying to keep the data saved on all components, but I'm still missing some.

**Comment by Archtica** [comment]
Fixed in next beta
