### ISSUE TITLE
Animation jumping

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#28]
1. follow a rhino perspective
2. play an animation through grashopper 
3. **Radii viewer jumps between the animation and the rhino perspective while going through the animation**

this assumption is based on the video that i have put in. picture 2 is from the video 3 the start position that seems similar

https://github.com/Archtica/RADii/assets/45074510/f8b99267-4737-453a-a607-72d69789ddd9

![Screenshot 2023-08-14 143357](https://github.com/Archtica/RADii/assets/45074510/a65605c3-d895-4683-9d94-a346192862bf)
![Screenshot 2023-08-14 143351](https://github.com/Archtica/RADii/assets/45074510/2a0565aa-38b2-4aef-8c99-f26d3bee6bde)
![Screenshot 2023-08-14 143438](https://github.com/Archtica/RADii/assets/45074510/573befc3-bc96-483e-a4d1-fba5e91ecb2b)

**Comment by Archtica** [comment]
Thank you, I should have solved it, but let me send out a new version tonight and test it again. Everything should be cancelled correctly now, but there could be situations where it is not.

**Comment by Archtica** [comment]
Please check with beta 6. I will test too.

**Comment by gesievi** [comment]
Will do Mit freundlichen Grüßen Gereon SieviAm 14.08.2023 um 22:39 schrieb Thomas Lee ***@***.***>:﻿
Please check with beta 6. I will test too.

**Comment by gesievi** [comment]
The issue seems to be persisting with me.

**Comment by Archtica** [comment]
Ok, I will have a look at it too. Thanks!

**Comment by Archtica** [comment]
I cannot reproduce it. Are you sure you are on the latest beta with both GH and Viewer? There used to be an issue just like that, but I fixed it a while ago. When you click the small "i" in the connect menu, make sure it says 0.36.8.0 on the standard viewer.
