### ISSUE TITLE
Radii viewer: Modell glitch when changing the time of day in grashopper scenario manager

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#35]
When changing the time of day in grasshopper with the scenario manager i get the following glitch. 

https://github.com/Archtica/RADii/assets/45074510/7e15bed3-7efd-4ad7-add5-83f3adca7943

**Comment by Archtica** [comment]
I've never seen that before!... are you changing with the slider or through Rhino built in?

**Comment by gesievi** [comment]
I am changing it with the slider in rhino grashopper. The glitch reminds me in appearance a bit on the one with follow + grashopper animation

**Comment by Archtica** [comment]
I cannot reproduce it. Are you doing something else just before or while doing it?

**Comment by Archtica** [comment]
Have you defined an origin rotation in the control component or have you also set the Rhino built in location? It looks like it's trying to do both.

![image](https://github.com/Archtica/RADii/assets/33350816/3d5f2818-71fc-4478-9cea-63ec8ffc6718)

**Comment by gesievi** [comment]
I found the error, it lays in the origin rotaion, all values different than 90 make it happen. It seems to jump between 90 and the other value ?
the sun location is not set.
![image](https://github.com/Archtica/RADii/assets/45074510/65646d32-e5ec-43c2-919b-81195381845c)

**Comment by Archtica** [comment]
Still cannot make it happen. What number are you setting in origin rotation? Could you maybe film both how you operate grasshopper and the result in the viewer behind it. Just have the grasshopper window over the viewer.

**Comment by gesievi** [comment]
I think this might be an issue with the scenarios that i loaded beforehand and then deleted. After loading a new scenario manager component i can also not reproduce this bug, i think we can close it for now. Very strange.

**Comment by Archtica** [comment]
Ok, so it's when firing scenarios with two different origin rotations maybe? I will play around with it and see if I can trigger it. If you can reproduce it with a sequence of steps, let me know.
What I did discover is that the daylight saving, when using the Rhino built-in location and time, is off, so I need to have a look at that 👍

**Comment by gesievi** [comment]
I was able to reproduce it:

1. Save a scenario in model rotation 90 
2. Load the scenario 
3. change the model rotation to any other degree 
4. change the time 
5. watch it glitching 


When i delete the scenario manager and reverse that step the glitch does not persist. 
Would post a video but windows standard recorder does not let me record specific windows.

**Comment by Archtica** [comment]
That's great G! Thank you that helps me a lot. I will look into it! 👍

**Comment by Archtica** [comment]
hmmm... I cannot reproduce it. Does the scenario trigger view too?

**Comment by Archtica** [comment]
https://github.com/Archtica/RADii/assets/33350816/a3d2747b-9b5f-4330-8a58-b5d7d5e4b29f

**Comment by gesievi** [comment]
considering that you could not reproduce it i would close the issue. 
I was able to reproduce it just now, but after rebuilding the setup i can also not reproduce it anymore. Might be a mix between old and new components on my side.
