### ISSUE TITLE
Viewer Radii grab conflicting with phyics and gravity 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#36]
When activating physics or gravity the grabbing tool does not work anymore, more precisely it becomes unusable.

**Comment by Archtica** [comment]
Thanks. I will have a look, I haven't tested that part for a while.

**Comment by Archtica** [comment]
I can confirm that you cannot grab gravity or physics objects. Something happened along the way it seems. I will fix it.

**Comment by Archtica** [comment]
Fixed in next beta release
