### ISSUE TITLE
Radii Viewer - animation stopping on right click

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#37]
When animating content the Animation stops as soon as you open a menu, it would be great if this would not be the case.

**Comment by Archtica** [comment]
That is part of the new "presentation mode". Whenever something is triggered from a control component like an animation, view, scenario etc. it goes into this mode hiding unnecessary UI items. Right clicking or escaping cancels it. The idea is that this is where you sit back and allow someone else to take control.
Maybe I should consider whether it was started by someone else or yourself. If it is self-triggered then right clicking is allowed while you are being animated, moving to view etc.

**EDIT**: sorry I didn't read it correctly! It should not cancel content animation, that's a bug. Thank you!

**Comment by Archtica** [comment]
Fixed in next release
