### ISSUE TITLE
 Viewer Not Clipping for curves

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#44]
Clipping seems to ignore curves in the AR Viewer and the PC viewer. 
Fotos of the IOs viewer are attached. Workes great beside this issue. 

![photo_2023-09-04_17-17-41](https://github.com/Archtica/RADii/assets/45074510/a134557e-871a-4432-94ec-d4ff9e375243)
![photo_2023-09-04_17-15-33](https://github.com/Archtica/RADii/assets/45074510/303926cf-e3ff-4799-b6fc-4b35476863d0)
![photo_2023-09-04_17-17-43](https://github.com/Archtica/RADii/assets/45074510/c726512b-f88c-4e56-97e4-5e45c0e99880)

**Comment by Archtica** [comment]
Yes, it requires more work in general with line weights and performance optimization. It's pretty bad if you have many lines. I don't think it is used very much, so I haven't given it much attention, but I will at one point.

**Comment by Archtica** [comment]
Line weights have been added, but I don't know how I would add line sectioning since it is using the unity built in renderer.
