### ISSUE TITLE
Grashopper Viewer shared geometry not there 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#45]
When publishing geometry with the shared option, it does not show up in the viewer even though it is noted that meshes where loaded. 
Can you reproduce this bug ?

**Comment by Archtica** [comment]
Do you mean shared geometry in the geometry subscribe component of GH? Or in a viewer?

**Comment by gesievi** [comment]
In the publish geometry component.
After that it does not appear in thr viewer.

**Comment by Archtica** [comment]
I'll check. Thanks!

**Comment by Archtica** [comment]
Hi G, I cannot reproduce it in the standard viewer. Is it any particular viewer where it doesn't work or did you do anything prior to it?
Also make sure that the checkbox on the publish menu is on. This shows/hides shared content in the scene. It will still receive but not display it until on.

![Screenshot 2023-09-05 212534](https://github.com/Archtica/RADii/assets/33350816/cd0cad1a-7435-40aa-8a03-cb490fbb7c5f)

**Comment by gesievi** [comment]
It must have been some other problem. I can not reproduce it either.
