### ISSUE TITLE
Radii Viewer Mac

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#48]
Visual Bug the image appears jittered and then black on certain mac laptops in our observed case a mac book pro, when the weather quality is all but the lowest. Image will follow.

**Comment by Archtica** [comment]
Is it consistent on all mac's or one in particular?

**Comment by gesievi** [comment]
it was particularly bad on one mac, on another i have seen a version that turned all the models green.

**Comment by Archtica** [comment]
Is this with this version in particular or something you seen with previous versions too?

**Comment by gesievi** [comment]
so far have only seen it in this version and on mac. As i said there is a workaround in the version, already by adjusting the settings, but i wanted to track this in case it is a persisting issue.

**Comment by Archtica** [comment]
Ok, thanks, but just to be clear it's only on some mac's or on all?

**Comment by gesievi** [comment]
on two macs, they have similar but not the same display issues.

**Comment by Archtica** [comment]
Ok, I will test on my mac too. Please take a screen shot if you can. It is related to the weather system somehow.

**Comment by Archtica** [comment]
I cannot reproduce. This is on a mac book pro (Intel). 
Are they looking at some particular type of geometry?
Are they in follow mode while it happens?
Is it all the time (when not in lowest weather quality)?
<img width="1076" alt="Screenshot 2023-09-26 at 20 36 31" src="https://github.com/Archtica/RADii/assets/33350816/88940c97-6ede-4257-951a-184d95e90d2f">

**Comment by gesievi** [comment]
The bug was all the time when not in lowest weather quality and after restarting the client.
Not in follow mode, the geometry  that was present was all the first works of all the students on the server.
If you can not reproduce it, ill try next week with her machine again and try to find out what precisely are the conditions for this bug. 
<img width="694" alt="Bildschirm_foto 2023-09-26 um 11 49 48" src="https://github.com/Archtica/RADii/assets/45074510/f47a2ad7-d20a-45f8-9034-d1ff8b1f538f">

**Comment by Archtica** [comment]
What!! That looks crazy! I've never seen that before. Why do you think the brown elements are not behaving like this, is it because the others have textures?
It's strange because the software is tested thoroughly before being accepted on the app store.
EDIT: So the geometry that behaves like this was made with a previous plugin version? '_the geometry that was present was all the first works of all the students on the server_'

**Comment by gesievi** [comment]
I think it could be the texture or a performance issue ? I asked the student if the issue persists with her until then i would consider this issue closed.
