### ISSUE TITLE
Browser is not displaying geometry and subchannel that has been created

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#53]
![image](https://github.com/Archtica/RADii/assets/45074510/3cf1c2db-e378-4a94-8ce7-12e6db04dd3f)
![image](https://github.com/Archtica/RADii/assets/45074510/badd433b-d09c-42cf-a018-6aee3d6294cf)

I assume this has something to do with the refresh rate of the website, it might be good to note the refresh rate on the browser to avoid confusion.

**Comment by gesievi** [comment]
PS: I was able to reproduce the error within 5 min of the issue beeing reported

**Comment by Archtica** [comment]
There is no refresh rate on the server. Once the file is there it will be there on radii.info/masdfab. Are the files in a subchannel of masdfab? Then it's a known issue. If the channel before the subchannel is empty it will not display the subchannel. If you place a file in masdfab it will show subchannels.
It's an old bug and I will fix it.

**Comment by gesievi** [comment]
I remember you mentioned this bug, ill check that with them.

**Comment by Archtica** [comment]
What subchannel are you trying to reach and is channel above that empty? If so, that is a display bug of the radii.info homepage, that I need to fix asap, because it is causing confusion. As said if the channel above is not empty it will display correctly.

**Comment by Archtica** [comment]
Fixed and pushed to radii.info including an "Up" button to move up from sublayers.
