### ISSUE TITLE
v037-b Clipping plane does not flip direction

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#65]
When flipping rhino Clipping planes, the direction change is not updated to the viewer.
![image](https://github.com/Archtica/RADii/assets/45074510/a03724df-a455-4f0c-9daa-80c7e20b2240)
![image](https://github.com/Archtica/RADii/assets/45074510/d396de36-f96f-4fd1-83d0-de0ef3de7984)

**Comment by Archtica** [comment]
This is a known issue. If you rotate it manually 180 degrees, with rotation or the gumball, radii will detect the change, doing just the normal flip will not. This is a general issue also with geometry. I am looking into detecting it properly, but for now do the manual 180 rotation.

**Comment by gesievi** [comment]
this was included in the documentation and can be closed for now.

**Comment by Archtica** [comment]
Let's keep it open. I will look into it at some point
