### ISSUE TITLE
Pointcloud Limitation in Scenario Manager

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#80]
Students report a limitation of 3 for Pointclouds in the Scenario Manager. It is unclear if this is intentional. they also report that it is not size related since they where able to merge the clouds and then save them as one.

**Comment by Archtica** [comment]
That is not an intentional limitation, but must be a bug. I will look into it and see if I can reproduce. Thanks!

**Comment by Archtica** [comment]
I also discovered this bug today. I will look into very soon.

**Comment by Archtica** [comment]
Fixed
