### ISSUE TITLE
R8 Grashopper connection

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#81]
R8 Radii is connecting to the server but seems to have an issue coming through to the viewer. Viewers do not seem to get a connection to R8 Radii
![image](https://github.com/Archtica/RADii/assets/45074510/92159048-f5e6-4b15-b260-ee47cb4ebc17)
Does not show up in the viewer as user or with geometry. 

Issue is Waiting to be reproduced.

**Comment by gesievi** [comment]
@Archtica reported that the issue has been fixed, needed some tweaking and should work now for R8.

**Comment by Archtica** [comment]
In current beta for both mac and windows
