### ISSUE TITLE
Radii Web: You can select multiple user to edit or delete - but only the first is actually changed

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#90]
Input:
![image](https://github.com/Archtica/RADii/assets/45074510/af935c5e-4e23-4805-aa46-ab68e7a79a7b)
Response to change of role, but the same for deleting users from channel. 
![image](https://github.com/Archtica/RADii/assets/45074510/14f67a41-f683-4575-8f8c-354b9c536a36)

**Comment by Archtica** [comment]
Fixed
