### ISSUE TITLE
Grashopper Mac Bug, Publish controll Load file 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#99]
I observed yesterday:
The publish control component on a mac device, did not allow for load commands from other channels than the one she was currently on.

Did not check her account status nor if this was potentially an installation error.

![photo_2024-03-06_09-19-38](https://github.com/Archtica/RADii/assets/45074510/33a1c213-47a6-42fe-aa96-3d8f0a13ccac)

**Comment by Archtica** [comment]
Does the path she is browsing exist? I can see it's j1020. That does not sound like a domain. She needs to put in the entire path ie. **gkrstudio.hs24.j1020** and then hit "Get files". Windows users can hit enter, but mac users must click the button. Hitting enter is not registered on mac.
The path is not relative to the one she is logged into like the save component. It can be anything. She is most likely browsing a domain that doesn't have any content or doesn't exist -> https://radii.info/j1020

**Comment by Archtica** [comment]
Oh wait, that channel does exist and has two files. My bad. Did she remember to hit the "Get files" button when on a mac. It will not refresh the file list until she does that.

**Comment by gesievi** [comment]
Clicking the get files button on mac could actually be the issue. I will ask her to try this.

**Comment by gesievi** [comment]
pressing load file instead of enter on mac solved the  issue. 
thank you for the hint. I will put this into the documentation. now

**Comment by Archtica** [comment]
Yes, it's a mac thing not accepting enter as an action. That is why all input fields have a corresponding button called "Set x..." for the mac users.
